# Generated by Django 3.1.5 on 2021-01-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.TextField(verbose_name='address')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('website', models.CharField(max_length=250, verbose_name='website')),
                ('company', models.TextField(verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
